garbageproject/garbageapp/urls.py
from django.urls import path
from . import views
 
app_name = 'garbageapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('types/', views.types, name='types'),
    path('booking/', views.booking, name='booking'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('map/', views.map, name='map'),
    path('plant/<int:plant_id>/', views.plant, name='plant'), 
    path('payment/',views.payment,name='payment'),
    path('success/',views.success,name='success'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<uuid:token>/', views.reset_password, name='reset_password'),
    
]

garbageproject/garbageproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('garbageapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

garbageproject/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    About CGC  
{% endblock %}
{% block content %}
<div class="image-container">
    <h1 class="about"><i>ABOUT US</i></h1>
    <img class="background-image" src="{% static 'img/about.png' %}" alt="about-image">
</div>
<div>
    <section class="sample-text-area">
        <div class="container">
            <p> Kozhikode, also known as Calicut, is a city in the state of Kerala, India. It is located on the Malabar coast and is known for its rich history and cultural heritage.
                The city was once the capital of the Zamorin kings and later a key location during British colonial rule. Today, it is a bustling urban area with a blend of historical charm and modern development.
            <br><br>
                Calicut Garbage Collection is a Waste Management Technology startup dedicated to addressing the pressing waste issues faced by society and the environment as a whole.
                Our vision is clear : to become the ultimate destination for the disposal of all types of waste, making it easier for everyone to contribute to a cleaner, greener future. 
                Our aim is to make a sustainable eco-friendly future, reduce environmental impact, and enhance resource efficiency.
            <br><br>
                With a satisfied customer base exceeding thousand,Calicut Garbage Collection stands as a prominent player in Kerala's waste management sector.
                A sustainable eco-friendly future with zero waste is the main mission of CGC..
                Calicut Garbage Collection's vision is to be a global leader in the transformation of waste management, leading the charge toward a world where waste is no longer a problem but a solution
            </p>
        </div>
    </section>
</div>
{% endblock %}

garbageproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="https://kit.fontawesome.com/8b8ca58c15.js" crossorigin="anonymous"></script>
    <title> {% block title %} {% endblock %} </title>
</head>
<body>
    <div>
        <div class="sticky-top" >
            <header class="header1">
                <img src="{% static 'img/logo.png' %}" alt="logoimage" height="62px" width="115px">
                <i class="fa-sharp fa-solid fa-location-dot"></i>
                <h style="margin-right: 3rem;">Calicut Garbage Collection</h>
                <i class="fa-solid fa-envelope"></i>
                <h>mycltgarbage@gmail.com</h>
                <a href="https://www.facebook.com/profile.php?id=61563953764716"><i class="fa-brands fa-facebook-f" style="margin-left: 45rem;color:white;"></i></a>
                <a href="https://www.instagram.com/my_cgc_2024?utm_source=qr&igsh=ZW5xd241eTVzcHU2"><i class="fa-brands fa-instagram social"></i></a>
                <a href="https://www.linkedin.com/in/calicut-garbage-collection-bab282322?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"><i class="fa-brands fa-linkedin-in social"></i></a>
            </header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
                <h class="clt">My Calicut</h>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item" style="margin-left: 15rem;">
                            <a class="nav-link text-dark" aria-current="page" href="{% url 'garbageapp:index' %}">HOME</a>
                        </li>
                        <li class="nav-item" style="margin-left: 2.5rem;">
                            <a class="nav-link text-dark" href="{% url 'garbageapp:about' %}">ABOUT</a>
                        </li>
                        <li class="nav-item" style="margin-left: 2.5rem;">
                            <a class="nav-link text-dark" href="{% url 'garbageapp:contact' %}">CONTACT US</a>
                        </li>
                        {% if request.session.user %}
                        <li class="nav-item" style="margin-left: 2.5rem;">
                            <a class="nav-link text-dark" >WELCOME&nbsp;&nbsp;{{ request.session.user.username|upper }}!</a>
                        </li>
                        <li class="nav-item" style="margin-left: 2.5rem;">
                            <a class="nav-link text-dark" href="{% url 'garbageapp:logout' %}">LOGOUT</a>
                        </li>
                        {% else %}
                        <li class="nav-item" style="margin-left: 2.5rem;">
                            <a class="nav-link text-dark" href="{% url 'garbageapp:login' %}">LOGIN</a>
                        </li>
                        {% endif %}
                    </ul>
                <!-- <form class="d-flex search1" role="search" action="#" method="get">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit"  style="margin-left: 1rem;"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form> -->
            </div>
        </nav>
    </div>
       
        {% block content %}
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>

        <footer>
            <div class="footer1" style="background-color: #e4e5f8 ">
                <p> &copy; Calicut Garbage Collection. All rights reserved </p>
            </div>
        </footer>
    </div>
</body>
</html>

garbageproject/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    contact CGC  
{% endblock %}
{% block content %}
<div class="image-container">
    <h1 class="about"><i>CONTACT US</i></h1>
    <img class="background-image" src="{% static 'img/contact.png' %}" alt="about-image">
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 card cnt-box1" style="margin-top: 20px;">
            <p style="font-size: 18px;">Have something in your mind you're interested in discussing with us? Drop us a line below, we’d love to talk.</p>
            <div class="shadow card cnt-box2">
                <div class="card-body">
                    <span class="icon"> <i class="fas fa-map-marker-alt"></i> </span>
                    <h4 class="cnt-text">Head office address :</h4>
                    <h6  class="cnt-text">Arakkinar P.O, Beypore, Calicut 673028</h6>
                </div>
            </div>
            <div class="shadow card cnt-box2">
                <div class="card-body">
                    <span class="icon"> <i class="fas fa-phone-volume"></i> </span>
                    <h4 class="cnt-text">Mobile Number:</h4>
                    <h6  class="cnt-text">9778021712</h6>
                </div>
            </div>
            <div class="shadow card cnt-box2">
                <div class="card-body">
                    <span class="icon"> <i class="fas fa-envelope-open-text"></i> </span>
                    <h4  class="cnt-text">Email Address :</h4>
                    <h6  class="cnt-text">cltgarbage@gmail.com</h6>
                </div>
            </div>
        </div>
        <div class="col-md-6 card cnt-box1">
            <div class="contact-bcimg" style="background-image: url('https://img.freepik.com/premium-photo/bright-green-meadow-with-grass_124507-13850.jpg');">
                
                <form id="contactusform" class="contact-form" action="" method="post" role="form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="text" name="name" placeholder="Name" class="cnt-frm">
                    <input type="number" id="phone" name="phone" class="cnt-frm" placeholder="Mobile Number" pattern="[0-9]{5}[0-9]{5}" required>
                    <br><br>
                    <input type="email" name="email" placeholder="Email" style="width: 100%;" class="cnt-frm">
                    <br><br>
                    <textarea rows="8" placeholder="Enter Message" name="message" style="width: 100%;height:150px;padding-top:30px;" class="cnt-frm"></textarea>
                    <br><br>
                    <input type="submit" value="Submit" class="cnt-frm-btn">
                </form>
              
            </div>
        </div>
        {% if messages %}
        <div>
            {% for message in messages %}
                <div class="message {{ message.tags }}" style="margin-top: -690px;margin-left: 515px;font-size: 22px;">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}   
    </div>
</div>            
{% endblock %}  
              
               

garbageproject/templates/forgot_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    Forgot Password
{% endblock %}
{% block content %}
<style>
    .toggle-panel.toggle-right {
        background-image: url("{% static 'img/forgot.avif' %}");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
</style>
<div class="log-sec1">
   <div class="container log-sec2" id="container" >
        <div class="form-container sign-in">
            <form action="{% url 'garbageapp:forgot_password' %}" method="post">
                {% csrf_token %}
                <h1 style="font-family: 'Times New Roman', Times, serif;font-weight: bold;margin-top: -10px;">Forgot Password</h1>
                <input type="email" name="email" placeholder="Enter your email" style="margin-top: 30px;">
                <button type="submit" style="margin-top: 25px;background-color: rgb(21, 3, 110);">Submit</button>
            </form>
        {% if messages %}
            <div class="message-box">
                {% for message in messages %}
                    <div class="message {{ message.tags }}" style="margin-top: 50px;margin-left: 20px;">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        </div>
        <div class="toggle-container" style="border: 2px solid black;">
            <div class="toggle">
                <div class="toggle-panel toggle-right">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

garbageproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    Sign In
{% endblock %}
{% block content %}
<div class="log-sec1">
   <div class="container log-sec2" id="container">
        <div class="form-container sign-in">
            <form action="{% url 'garbageapp:login' %}" method="post">
                {% csrf_token %}
                <h1 style="font-family: 'Times New Roman', Times, serif;font-weight: bold;margin-left: 30px;">Sign In</h1>
                <input type="email" placeholder="Email" name="email">
                <input type="password" placeholder="Password" name="password">
                <a href="{% url 'garbageapp:forgot_password' %}" style="color: black;margin-top: 15px;text-decoration: none;">Forgot your password?</a>
                <button type="submit" style="margin-top: 15px;">Log In</button>
            </form>
        {% if messages %}
            <div class="message-box">
                {% for message in messages %}
                    <div class="message {{ message.tags }}" style="margin-top: 30px;margin-left: -25px;">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-right">
                    <h1 style="font-family: 'Times New Roman', Times, serif;font-weight: bold;">Hello,Friend!</h1>
                    <p>If you don't have an account</p>
                    <a href="{% url 'garbageapp:register' %}"><button>Sign Up</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

garbageproject/templates/map.html
<!DOCTYPE html>
<html>
<head>
    <title>CGC Plantation Map</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />  <!--leaflet a flexible, lightweight, and open-source JavaScript library for creating interactive maps. -->
    <style>
        #map {
            height: 500px;
            width: 100%;
            font-size: 15px;
            font-weight: bold;
        }
        .map-sec1 {
            margin-top: 30px;
            color: rgb(124, 4, 4);
            font-weight: bold;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1 class="map-sec1">Available Plants In Calicut</h1>
    <div id="map" ></div>
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script>
        // Initialize the map centered on Calicut
        var map = L.map('map').setView([11.2588, 75.7804], 13); // Coordinates for Calicut city. (latitude 11.2588, longitude 75.7804) with a zoom level of 13.

        // Add tile layer from OpenStreetMap
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '© OpenStreetMap contributors'
        }).addTo(map);

        // Define scattered locations with random placement
        var locations = [
            { lat: 11.2350, lng: 75.7880, popup: 'Kallai',link: '/plant/',id:5},
            { lat: 11.3305, lng: 75.7905, popup: 'Balussery',link: '/plant/',id:2 },
            { lat: 11.2500, lng: 75.7740, popup: 'Mananchira',link: '/plant/',id:4 },
            { lat: 11.2650, lng: 75.8100, popup: 'Thondayad',link: '/plant/',id:1 },
            { lat: 11.1805, lng: 75.8100, popup: 'Beypore',link: '/plant/',id:7},
            { lat: 11.3000, lng: 75.7630, popup: 'puthiyangadi',link: '/plant/',id:3 },
            { lat: 11.2300, lng: 75.8500, popup: 'pantheerankave',link: '/plant/',id:6 }
        ];

        locations.forEach(function(location) {
            L.marker([location.lat, location.lng]).addTo(map)
            .bindPopup('<a href="/plant/' + location.id + '/">' + location.popup + '</a>');
});

    </script>
</body>
</html>

garbageproject/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    CGC Payment  
{% endblock %}
{% block content %}
<div class="image-container">
    <h1 class="about"><i>MAKE PAYMENT</i></h1>
    <img class="background-image" src="{% static 'img/payment.png' %}" alt="about-image">
</div>
<div class="shadow card text-center" style="width: 600px; height:300px;margin-left: 450px;margin-bottom: 50px;background-color: #e8edfd;">
    <form action="{% url 'garbageapp:success' %}" method="POST" >
        {% csrf_token %}
        <div class="card-body pay-sec1">
            <h5 class="card-title">Waste Type : <b>{{waste_type }}</b></h5>
            <h5 class="card-title">Total Weight : <b>{{ weight }} kg</b></h5>
            <h5 class="card-title">Minimum Service Charge: <b>Rs. 100/-</b></h5>
            <h5 class="card-title">Total Amount: <b>Rs. {{ amount }}/-</b></h5>
        </div>
        <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_JAeLcxoJpwFjEq"
        data-amount="{{ amount|floatformat:0 }}00" data-currency="INR" data-order_id="{{payment.id}}" data-buttontext="Make Your Payment"
        data-name="Professional Cipher" data-description="Django and Data Science"
        data-image="https://example.com/your_logo.jpg" data-prefill.name="PC" data-prefill.email="pc@studygyaan.com"
        data-theme.color="#F37254"></script>
    </form>
<style>
    .razorpay-payment-button {
        background-color: #1a8f2c;
        color: white;
        font-size: 18px;
        border: none;
        border-radius: 8px;
        padding: 12px 24px;
        cursor: pointer;
        transition: background-color 0.3s ease;
        margin-top: 10px;
}
</style>
</div>
{% endblock %}

garbageproject/templates/plantation.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    CGC Plantations
{% endblock %}
{% block content %}
<div class="image-container">
    <h1 class="about"><i>{{ detail.pname }} Plantation</i></h1>
    <img class="background-image" src="{% static 'img/plantation.png' %}" alt="about-image">
</div>
<div>
    <section class="sample-text-area">
        <div class="container">
            <p>{{ detail.desc }}</p>
        </div>
    </section>
    <div>
    <a href="{% url 'garbageapp:payment' %}" style="text-decoration: none;color: black;"><button type="submit" class="btn plant-sec1">Make Payment</button></a>
    </div>
</div>
{% endblock %}

garbageproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    Sign Up
{% endblock %}
{% block content %}
<div class="log-sec1">
   <div class="container log-sec2" id="container">
        <div class="form-container sign-in">
            <form action="" method="post">
                {% csrf_token %}
                <h1 style="font-family: 'Times New Roman', Times, serif;font-weight: bold;">Create Account</h1>
                <!-- <div class="social-icons">
                    <a href="" class="icon1"><i class="fa-brands fa-google-plus-g"></i></a>
                </div> -->
                <!-- <span>or use your email for registration</span> -->
                <input type="text" placeholder="Username" name="username" style="margin-top: 25px;">
                <input type="email" placeholder="Email" name="email">
                <input type="password" placeholder="Password" name="password">
                <input type="password" placeholder="Confirm Password" name="cpassword">
                <br>
                <button type="submit" style="margin-top: -2px;">Sign Up</button>
            </form>
            {% if messages %}
            <div class="message-box">
                {% for message in messages %}
                    <div class="message {{ message.tags }}" style="margin-top: 3px;margin-left: 10px;">{{ message|safe }}</div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-right">
                        <h1 style="font-family: 'Times New Roman', Times, serif;font-weight: bold;">Welcome Back!</h1>
                        <p>If you already have an account</p>
                        <a href="{% url 'garbageapp:login' %}"><button>Log In</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

garbageproject/templates/reset_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    Reset Password
{% endblock %}
{% block content %}
<style>
    .toggle-panel.toggle-right {
        background-image: url("{% static 'img/reset.jpg' %}");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
</style>
<div class="log-sec1">
   <div class="container log-sec2" id="container" >
        <div class="form-container sign-in">
            <form action="" method="post">
                {% csrf_token %}
                <h1 style="font-family: 'Times New Roman', Times, serif;font-weight: bold;margin-top: -10px;">Reset Password</h1>
                <input type="password" name="password" placeholder="New Password" style="margin-top: 30px;">
                <input type="password" name="cpassword" placeholder="Confirm New Password">
                <button type="submit" style="margin-top: 25px;background-color: rgb(21, 3, 110);">Reset Password</button>
            </form>
        {% if messages %}
            <div class="message-box">
                {% for message in messages %}
                    <div class="message {{ message.tags }}" style="margin-top: 30px;margin-left: -15px;">{{ message|safe }}</div>
                {% endfor %}
            </div>
        {% endif %}
        </div>
        <div class="toggle-container" style="border: 2px solid black;">
            <div class="toggle">
                <div class="toggle-panel toggle-right">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

garbageproject/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Success</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            color: #333;
        }
        .container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            max-width: 500px;
            padding: 50px;
            text-align: center;
        }
        .container h1 {
            color: #4CAF50;
            margin-bottom: 20px;
        }
        .container p {
            font-size: 18px;
            margin-bottom: 30px;
        }
        .container .success-icon {
            font-size: 60px;
            color: #4CAF50;
            margin-bottom: 20px;
        }
        .container .btn {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            font-size: 18px;
        }
        .container .btn:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="success-icon">✔️</div>
        <h1>Payment Successful!</h1>
        <p>Thank you for your payment. Your transaction has been successfully completed.</p>
        <a href="/" class="btn">Go to Homepage</a>
    </div>
</body>
</html>

garbageproject/templates/waste-type.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
    Types of Garbages 
{% endblock %}
{% block content %}
<div class="image-container">
    <h1 class="about"><i>TYPES OF GARBAGES</i></h1>
    <img class="background-image" src="{% static 'img/types.png' %}" alt="about-image">
</div>
<div>
    <div class="container">
        <div class="row mx_auto">
            <div class="col-12 col-md-4 type-sec1">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                    <img class="card-img-top" src="{% static 'img/bio-degradable.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title" style="text-align: center;">bio-degradable</h2> 
                        <p class="card-text">These substances are non-toxic to the environment comprising of only natural materials. 
                                             Examples include food scraps, paper, and plant materials.</p>
                        {% if request.session.user %}
                        <a href="{% url 'garbageapp:booking' %}"><button class="btn type-sec2">
                                        Book Now
                                   </button>
                        </a>
                        {% else %}
                        <a href="{% url 'garbageapp:login' %}"><button class="btn type-sec2" style="width: 200px;margin-left: 35px;">Log In For Booking</button></a> 
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4 type-sec1">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                    <img class="card-img-top" src="{% static 'img/non-biodegradable.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title" style="text-align: center;">non-biodegradable</h2> 
                        <p class="card-text">These are materials that cannot be easily broken down by natural processes 
                                        and persist in the environment for a long time. Examples include plastics, glass, and metals.</p>
                        {% if request.session.user %}
                        <a href="{% url 'garbageapp:booking'%}"><button class="btn type-sec2" style="margin-top: 8px;">
                                        Book Now
                                    </button>
                        </a>
                        {% else %}
                        <a href="{% url 'garbageapp:login' %}"><button class="btn type-sec2" style="width: 200px;margin-left: 35px;margin-top: 7px;">Log In For Booking</button></a> 
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4 type-sec1">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                    <img class="card-img-top" src="{% static 'img/hazardous.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title" style="text-align: center;">hazardous</h2> 
                        <p class="card-text">These are materials that pose a significant risk to human health or the environment. 
                                        Examples include chemicals, batteries, and certain industrial by-products.</p>
                        {% if request.session.user %}
                        <a href="{% url 'garbageapp:booking' %}"><button class="btn type-sec2">
                                            Book Now
                                   </button>
                        </a>
                        {% else %}
                        <a href="{% url 'garbageapp:login' %}"><button class="btn type-sec2" style="width: 200px;margin-left: 35px;">Log In For Booking</button></a> 
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}